### ISSUE TITLE
Additional examples django setup configuration

### ISSUE THREAD

**Issue by SilviaAmAm** [open-zaak/open-notificaties#241]
### Thema / Theme

Other

### Omschrijving / Description

I see that there are still some #TODO in the documentation on django setup configuration.

I received some feedback from Dimpact that it would be good to have examples on how to configure the `notifications_abonnementen_config`, especially in the case of the bearer token. For example:

```yaml
      notifications_abonnementen_config_enable: true
      notifications_abonnementen_config:
        items:
          - uuid: b5d5abcb-b95c-4367-913e-6b90b28b9d8b
            callback_url: https://zac.example.nl/rest/notificaties
            auth: zaczaczac
            kanalen:
              - naam: objecten
              - naam: zaken
              - naam: documenten
              - naam: besluiten
          - uuid: e6983a51-0315-4ed3-b991-b54eb363bec9
            callback_url: https://notificaties.example.nl/api/v1/callbacks
            auth: Bearer token
            kanalen:
              - naam: autorisaties
```

So maybe when the rest of the documentation is updated, this could be included.

Also, it is tricky to configure Open Notificaties and Open Zaak to talk to each other properly. Not sure where would be the best place to place an example for configuring them both 🤔 

### Aanvullende opmerkingen / Additional context

Question: at the moment, the setup configuration docs are only visible in the "1.8.0" version of the docs (on RTD), but not on the version "latest". Is this expected? 🤔
