### ISSUE TITLE
Notfication delivery retry mechanism may not be configurable

### ISSUE THREAD

**Issue by KevinKemkes** [open-zaak/open-notificaties#246]
### Product versie / Product version

1.8.0

### Omschrijf het probleem / Describe the bug

Using the helm chart provided by Maykin we attempted to configure the retry mechanism. However, it may have no effect.

### Stappen om te reproduceren / Steps to reproduce

1. set the retry mechanism variables in the Helm Chart

![Image](https://github.com/user-attachments/assets/428baddf-0e82-4f90-aa62-95db8c7600ea)

2. Note that the variables are present in the configmap generated as a result of the Helm Chart

3. Note that the variables are present in the container using printenv (I copied the relevant variables to reduce the length of this issue):

NOTIFICATION_DELIVERY_RETRY_BACKOFF=30
NOTIFICATION_DELIVERY_RETRY_BACKOFF_MAX=600000
NOTIFICATION_DELIVERY_MAX_RETRIES=6

4. Note, however, that the retries are following the default schedule

![Image](https://github.com/user-attachments/assets/3c0ea541-768a-4c48-a242-c886e74aaa00)

**Comment by stevenbal** [comment]
These settings are no longer configurable via envvars, but must be configured with setup-configuration. I do see that the chart for Open Notificaties has something in place for setup configuration, but I'm not sure if the way it's configured there is correct? https://github.com/maykinmedia/charts/blob/main/charts/opennotificaties/values.yaml#L11-L32. @SilviaAmAm do you know what needs to be changed in that chart to make sure setup-configuration is run?

The following data would have to be added to configure the retry settings
```yaml
notifications_config_enable: true
notifications_config:
  notification_delivery_max_retries: 5
  notification_delivery_retry_backoff: 3
  notification_delivery_retry_backoff_max: 48
```
